service:
  name: backend

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1
  environment:
    AUTH0_CLIENT_ID: ${env:AUTH0_CLIENT_ID}
    AUTH0_CLIENT_SECRET: ${env:AUTH0_CLIENT_SECRET}
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
  adminUsers:
    handler: handler.adminUsers
    events:
      - http:
          method: get
          path: admin-users
  putUser:
    handler: handler.putUser
    events:
      - http:
          method: put
          path: user
